version: '3'
services:
  grafana:
    image: grafana/grafana:10.1.5-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    ports:
      - 9090:9090
    network_mode: host
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
